### ISSUE TITLE
Backpressure on FramedWrite senders

### ISSUE THREAD

**Issue by cbs228** [matthunz/futures-codec#13]
@najamelan, this issue follows up on discussion from #11.

This issue explores the need to apply "backpressure" in the Framer. Backpressure reduces the speed of a process which is *producing* data to that of the process which is *consuming* the data. In synchronous code, this is accomplished by blocking. In `async` code, this is accomplished by preventing input when the I/O is not yet ready for more. If backpressure is not applied, data will buffer forever—possibly until the sending system exhausts its available memory.

At present, `FramedWrite::start_send()` does not impose back-pressure on clients. Back-pressure is only applied during `FramedWrite::poll_write()` and `FramedWrite::poll_flush()`. The latter two poll calls may return `Poll::Pending` if the I/O has not yet completed. This will impose back-pressure on the sender.

There is an edge-case which is not handled by the present `FramedWrite`: **bottomless** streams. A bottomless stream always returns the next item and will never return `None`. Applications which may use bottomless streams include "live-streamed" media, which has no definite end.

`Sink::send_all()` will read an entire `Stream` and submit it all at once to the `Sink`. The [main loop](https://github.com/rust-lang-nursery/futures-rs/blob/db4cad36ecbf59868c195738333f6d841b342fa2/futures-util/src/sink/send_all.rs#L80) indicates that the Sink will only be flushed when either:

1. The source Stream is exhausted; OR
2. The source Stream blocks with `Pending`.

If the Stream never does either of these things, then the loop will run forever. I have a demonstration of this on my [`feature/write_backpressure`](https://github.com/cbs228/futures-codec/blob/051515b1567a48812692159ddbe31817a81255f3/src/framed_write.rs#L220) branch. In this test, my stream is limited so that it won't use all of your memory, but it does prove that all the data is provided to the I/O at once, at the end.

This kind of scenario might unfold when you are trying to send a file that you can read very quickly or send data that generates in memory. As long as the source never `Pending`s, the data will buffer forever, and the `FramedWrite` won't even try to start sending it to the I/O.

Tokio solves this issue by [limiting](https://github.com/tokio-rs/tokio/blob/d0bb16192b70be73eb7be3f5f7d9979c91e0f9a8/tokio-codec/src/framed_write.rs#L185) the amount of data that `start_send()` will accept before a flush is attempted.

I would like to propose adopting a similar behavior for `FramedWrite`, but with a twist: There is no need to flush the entire buffer. Instead, we should just try to `AsyncWrite::poll_write()` what we can. This should help guarantee that progress is made. We may need a caller-adjustable "high water mark" which sets the critical buffer length at which we start to do this.

**Comment by najamelan** [comment]
Thanks for looking into this and testing. It's a very instructive read. Unfortunately until the beginning of august I will be on the road, so I won't be able to contribute much until then!

**Comment by cbs228** [comment]
No worries. I might prepare something in the meanwhile. This issue addresses a corner case that is unlikely to occur in most scenarios. Usually, if your sending stream is bottomless, you'll be getting that data from some other I/O source. The generating source is likely to block eventually.

On linux, the kernel send buffer for TCP sockets (`SO_SNDBUF`) is capped to be no larger than `/proc/sys/net/core/wmem_max` bytes, which is 1,048,576 bytes for me. See [man 7 socket](http://man7.org/linux/man-pages/man7/socket.7.html). The default size is 212,992 bytes.

I haven't tested this, but I imagine that if you submit a `write(2)` larger than your `SO_SNDBUF`, the kernel won't work it all at once. You'll have some leftover. To wait deeper than your `SO_SNDBUF` size is to cause bufferbloat with no gain in throughput or reductions in number of syscalls. (If I misunderstand this, please correct me!)

212,992 bytes is a reasonable default high water-mark, if we want to add one.

**Comment by Nemo157** [comment]
I don't think this is such a corner case, it applies to very large streams as well as limitless streams. For instance if you're sending a large number of small items that are eventually 500MB when serialized, serializing all of that before flushing it out is a massive memory cost (and a smaller time cost because the connection is sitting idle while that data is serialized, instead of starting to send the first item while the rest is serialized, depends on the ratio between serialization rate and connection data rate). You may be getting the items from a source that creates them as needed so that with end-to-end backpressure you would only have a small fraction of that memory in use (e.g. a database connection that uses backpressure to read a limited number of rows into memory at a time).

**Comment by Nemo157** [comment]
> `Sink::send_all()` will read an entire `Stream` and submit it all at once to the `Sink`. The [main loop](https://github.com/rust-lang-nursery/futures-rs/blob/db4cad36ecbf59868c195738333f6d841b342fa2/futures-util/src/sink/send_all.rs#L80) indicates that the Sink will only be flushed when either:
> 
>     1. The source Stream is exhausted; OR
> 
>     2. The source Stream blocks with `Pending`.

Flushing in the second case seems slightly odd, I think that should be replaced with `poll_ready` instead as all that `SendAll` is interested in is that it can send another item, at the moment it may get a late wakeup if the sink is able to take another item but hasn't _fully_ flushed itself.

I think that's just a consequence of there not being separate `poll_ready` and `start_send` methods when it [was initially changed](https://github.com/rust-lang-nursery/futures-rs/blame/669980ba9215e6b1d50a730a3663629135bf2d06/futures-util/src/sink/send_all.rs) and nobody realising this and updating it since then.

**Comment by cbs228** [comment]
The above [topic branch](https://github.com/cbs228/futures-codec/blob/feature/write_backpressure/src/framed_write.rs) has a sample implementation for your consideration.

I have set the default high-water mark to 2^17 == 131072 bytes, which is somewhat under the default `SO_SNDBUF`. This is much larger than tokio's 8K, and it may be much larger than necessary.

Any opinions, guys? Should I convert this into a PR?
