### ISSUE TITLE
Publish new version to crates.io

### ISSUE THREAD

**Issue by expenses** [matthunz/futures-codec#30]
Hi, the `bytes` upgrade means that you lost backwards compatibility with old `bytes` versions. Please publish a new version as soon as possible.

**Comment by matthunz** [comment]
Oh my fault I didn't know that was the case. Just published!

**Comment by najamelan** [comment]
@matthunz I'm running into this as well. This happens because you have the Bytes type in your public interface. It means each time the bytes crate makes a breaking change version bump, so should you. 

In practice it would mean yanking the 0.3 versions of futures-codec that rely on bytes 0.5, and republishing the latest under futures-codec 0.4...

Otherwise the semver versions that cargo uses break dependent crates.
