### ISSUE TITLE
Unreasonable io::Error constraint

### ISSUE THREAD

**Issue by Proximyst** [matthunz/futures-codec#7]
The constraint on `Decoder::Error` (`type Error: From<io::Error>` - https://github.com/matthunz/futures-codec/blob/master/src/decoder.rs#L11) is, at least to me, unreasonable. This should be any kind of decoding error, given not all decoding errors are in fact related to `std::io::Error`.
One way of going about this would be to *always* return `Result<Self::Item, Self::Error>`, which would allow e.g. `Option<Packet>` or `Result<Packet, DecodeError>`, but having an Option which would always be `Some` is simply not something which should be accepted in such a design, if the error type might not be whatever type one would want.

**Comment by matthunz** [comment]
The `From<io::Error>` constraint is due to this line in `FramedRead`:
https://github.com/matthunz/futures-codec/blob/5321040773e254caad70f0280a8a8c10b5c29c57/src/framed_read.rs#L99

I suppose a constraint of `std::error::Error` might make more sense but I figured `io::Error` is pretty standard when dealing with streams
